### ISSUE TITLE
Adicionar a instrução WORKDIR

### ISSUE THREAD

**Issue by gwmoura** [edyonil/docker-php7fpm-phalcon#1]
@edyonil seria interessante adicionar a instrução `WORKDIR` no `Dockerfile` dessa forma o container já será iniciado na pasta definida no `WORKDIR`, dessa não precisaremos adicionar a instrução `woking_dir` em todos os `docker-compose.yaml`.

Outra vantagem seria no momento de executar comandos, precisaríamos executar somente `docker-compose run --rm php /vendor/bin/phpunit` ou se definirmos um name para o container poderemos até executar assim `docker exec [container_name] vendor/bin/phpunit`

Atualmente estou utilizando meu docker-compose.yaml desta forma:

```yaml
php:
        image: edyonil/php7fpm-phalcon
        working_dir: /home/projeto
        volumes:
            - ./:/home/projeto
```

Mas seria interessante usarmos assim:

```yaml
php:
        image: edyonil/php7fpm-phalcon
        volumes:
            - ./:/home/projeto
```

**Comment by edyonil** [comment]
Entendi George.. Vou adicionar essa instrução ao docker-composer. Realmente é mais prático, assim ao entrar no container não precisa navegar até a pasta do projeto. Como sou novo no Docker não sabia dessa instrução.

> Atualmente estou utilizando meu docker-compose.yaml desta forma:
```yaml
php:
        image: edyonil/php7fpm-phalcon
        working_dir: /home/projeto
        volumes:
            - ./:/home/projeto
```
A segunda opção é como está hoje. Eu entendi que o ideal seria a primeira opção não?
